name: straeto_speedometer
description: Real-time bus speed monitoring for Reykjavík
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  provider: ^6.1.5
  fl_chart: ^0.70.2
  file_picker: ^10.1.7
  idb_shim: ^2.8.2
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/speed_limits.geojson
