name: shared
description: Shared models and services for Straeto Speedometer
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  test: ^1.25.0
