name: collector
description: Straeto bus data collector CLI
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  shared:
    path: ../shared
  args: ^2.7.0
  http: ^1.6.0
  intl: ^0.20.2
